#!/usr/bin/env python3
"""Two agents, one file: the lost update, and how `write --if-sha256` prevents it.

    python3 scripts/demo_race.py                  # print the transcript
    python3 scripts/demo_race.py --update-readme  # write it into README.md
    python3 scripts/demo_race.py --check          # CI: the outcomes hold, and README.md is current

Two agents edit `notes.txt`, which holds one line. Each reads it, adds a line
of its own, and writes the result back; the second writes after the first, but
both read before either wrote.

* With plain writes (what `cat > file`, `cp` and `sed -i` do), the second write
  replaces the first, and agent A's line is gone without either agent being
  told.
* With `write --if-sha256`, each agent names the hash of the content it read.
  The second write is refused with `precondition.hash-mismatch` (exit 5),
  which carries the file's actual hash; the agent re-reads, re-applies its
  edit and writes again with the new hash. Both lines survive.

Everything below is the tools' real output, run in a scratch directory; the
transcript is deterministic (no clock, no paths outside --root), so the README
section is checked to be exactly what this script prints.
"""

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
README = ROOT / "README.md"
BEGIN = "<!-- demo-race:begin (generated by scripts/demo_race.py; do not edit) -->"
END = "<!-- demo-race:end -->"

ORIGINAL = b"shopping list\n"
LINE_A = b"- milk (agent A)\n"
LINE_B = b"- bread (agent B)\n"


def tool(name, *args, stdin=b"", cwd):
    p = subprocess.run([str(BUILD / name), *args], input=stdin, capture_output=True, cwd=cwd)
    return p.returncode, p.stdout.decode().strip()


def short(text, keep=12):
    """Shorten every 64-digit hash in `text` for display."""
    out, i = [], 0
    while i < len(text):
        chunk = text[i:i + 64]
        if len(chunk) == 64 and all(c in "0123456789abcdef" for c in chunk) and (i == 0 or not text[i - 1].isalnum()):
            out.append(chunk[:keep] + "…")
            i += 64
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


def classic(work):
    f = work / "notes.txt"
    f.write_bytes(ORIGINAL)
    a_read = f.read_bytes()
    b_read = f.read_bytes()
    f.write_bytes(a_read + LINE_A)
    f.write_bytes(b_read + LINE_B)
    final = f.read_bytes()
    lines = [
        "$ # A and B both read notes.txt, then each writes back what it read plus its own line",
        "$ printf 'shopping list\\n- milk (agent A)\\n'  > notes.txt   # agent A",
        "$ printf 'shopping list\\n- bread (agent B)\\n' > notes.txt   # agent B",
        "$ cat notes.txt",
        final.decode().rstrip("\n"),
    ]
    return lines, final


def guarded(work):
    f = work / "notes.txt"
    f.write_bytes(ORIGINAL)
    root = ["--root", "."]
    lines = ["$ hash --root . notes.txt        # A and B both read it, and both see H1"]
    status, out = tool("hash", *root, "notes.txt", cwd=work)
    lines.append(short(out.splitlines()[0]))
    h1 = json.loads(out.splitlines()[0])["hex"]

    lines.append("$ printf 'shopping list\\n- milk (agent A)\\n' | write --root . --if-sha256 H1 --stdin notes.txt   # agent A")
    status_a, out_a = tool("write", *root, "--if-sha256", h1, "--stdin", "notes.txt", stdin=ORIGINAL + LINE_A, cwd=work)
    lines.append(short(out_a))
    lines.append("$ printf 'shopping list\\n- bread (agent B)\\n' | write --root . --if-sha256 H1 --stdin notes.txt   # agent B, stale")
    status_b, out_b = tool("write", *root, "--if-sha256", h1, "--stdin", "notes.txt", stdin=ORIGINAL + LINE_B, cwd=work)
    lines.append(short(out_b))
    lines.append("$ echo $?")
    lines.append(str(status_b))

    # B recovers: re-read, re-apply its edit to what is there now, write with the new hash.
    current = f.read_bytes()
    h2 = json.loads(out_b)["error"]["detail"]["actual_sha256"]
    assert h2 == hashlib.sha256(current).hexdigest()
    lines.append("$ # agent B re-reads (the refusal carried the new hash, H2), re-applies its line, and retries")
    lines.append("$ printf 'shopping list\\n- milk (agent A)\\n- bread (agent B)\\n' | write --root . --if-sha256 H2 --stdin notes.txt")
    status_c, out_c = tool("write", *root, "--if-sha256", h2, "--stdin", "notes.txt", stdin=current + LINE_B, cwd=work)
    lines.append(short(out_c))
    final = f.read_bytes()
    lines.append("$ cat notes.txt")
    lines.append(final.decode().rstrip("\n"))
    return lines, final, (status_a, status_b, status_c), out_b


def transcript():
    with tempfile.TemporaryDirectory(prefix="demo-race-") as tmp:
        work = pathlib.Path(tmp)
        (work / "classic").mkdir()
        (work / "guarded").mkdir()
        classic_lines, classic_final = classic(work / "classic")
        guarded_lines, guarded_final, statuses, refusal = guarded(work / "guarded")
    md = [
        BEGIN,
        "",
        "**With plain writes**, the second write wins and agent A's line is gone. Nobody is told:",
        "",
        "```console",
        *classic_lines,
        "```",
        "",
        "**With `write --if-sha256`**, the stale write is refused, and the refusal carries what the agent needs to retry:",
        "",
        "```console",
        *guarded_lines,
        "```",
        "",
        END,
    ]
    outcome = {
        "classic_lost_a": LINE_A not in classic_final,
        "guarded_kept_both": LINE_A in guarded_final and LINE_B in guarded_final,
        "statuses": statuses,
        "refusal_rule": json.loads(refusal)["error"]["rule"],
    }
    return "\n".join(md) + "\n", outcome


def readme_with(section):
    text = README.read_text()
    if BEGIN not in text or END not in text:
        sys.exit("README.md has no demo-race markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + section.rstrip("\n") + tail


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--update-readme", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    for name in ("hash", "write"):
        if not (BUILD / name).exists():
            sys.exit(f"demo_race: build/{name} is missing; run `cancho build` first")
    section, outcome = transcript()
    problems = []
    if not outcome["classic_lost_a"]:
        problems.append("plain writes did not lose agent A's line")
    if not outcome["guarded_kept_both"]:
        problems.append("guarded writes did not keep both lines")
    if outcome["statuses"] != (0, 5, 0):
        problems.append("exit statuses were %s, not (0, 5, 0)" % (outcome["statuses"],))
    if outcome["refusal_rule"] != "precondition.hash-mismatch":
        problems.append("the stale write was refused as %s" % outcome["refusal_rule"])
    if args.update_readme:
        README.write_text(readme_with(section))
    elif args.check:
        if readme_with(section) != README.read_text():
            problems.append("README.md's demo section is not what the script prints; run --update-readme")
    else:
        print(section, end="")
    if problems:
        sys.exit("demo_race: " + "; ".join(problems))
    return 0


if __name__ == "__main__":
    sys.exit(main())
