#!/usr/bin/env python3
"""Two agents, one file: the lost update, and how `write --if-sha256` prevents it.

    python3 scripts/demo_race.py                  # print the transcript
    python3 scripts/demo_race.py --update-readme  # write it into README.md and docs/reference.md
    python3 scripts/demo_race.py --check          # CI: the outcomes hold, and README.md and docs/reference.md are current

Two agents edit `notes.txt`, which holds one line. Each reads it, adds a line
of its own, and writes the result back; the second writes after the first, but
both read before either wrote.

* With plain writes (what `cat > file`, `cp` and `sed -i` do), the second write
  replaces the first, and agent A's line is gone without either agent being
  told.
* With `write --if-sha256`, each agent names the hash of the content it read.
  The second write is refused with `precondition.hash-mismatch` (exit 5),
  which carries the file's actual hash; the agent re-reads, re-applies its
  edit and writes again with the new hash. Both lines survive.

Everything below is the tools' real output, run in a scratch directory; the
transcript is deterministic (no clock, no paths outside --root), so the README
sections are checked to be exactly what this script prints:

* docs/reference.md holds the full transcript (`demo-race` markers);
* README.md holds a short one, the same run with selected fields of each JSON
  line (`demo-flow` markers), and one real command per tool on a small project
  (`demo-tasks` markers).
"""

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
README = ROOT / "README.md"
REFERENCE = ROOT / "docs" / "reference.md"
BEGIN = "<!-- demo-race:begin (generated by scripts/demo_race.py; do not edit) -->"
END = "<!-- demo-race:end -->"
FLOW_BEGIN = "<!-- demo-flow:begin (generated by scripts/demo_race.py; do not edit) -->"
FLOW_END = "<!-- demo-flow:end -->"
TASKS_BEGIN = "<!-- demo-tasks:begin (generated by scripts/demo_race.py; do not edit) -->"
TASKS_END = "<!-- demo-tasks:end -->"

ORIGINAL = b"shopping list\n"
LINE_A = b"- milk (agent A)\n"
LINE_B = b"- bread (agent B)\n"


def tool(name, *args, stdin=b"", cwd):
    p = subprocess.run([str(BUILD / name), *args], input=stdin, capture_output=True, cwd=cwd)
    return p.returncode, p.stdout.decode().strip()


def short(text, keep=12):
    """Shorten every 64-digit hash in `text` for display."""
    out, i = [], 0
    while i < len(text):
        chunk = text[i:i + 64]
        if len(chunk) == 64 and all(c in "0123456789abcdef" for c in chunk) and (i == 0 or not text[i - 1].isalnum()):
            out.append(chunk[:keep] + "…")
            i += 64
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


def classic(work):
    f = work / "notes.txt"
    f.write_bytes(ORIGINAL)
    a_read = f.read_bytes()
    b_read = f.read_bytes()
    f.write_bytes(a_read + LINE_A)
    f.write_bytes(b_read + LINE_B)
    final = f.read_bytes()
    lines = [
        "$ # A and B both read notes.txt, then each writes back what it read plus its own line",
        "$ printf 'shopping list\\n- milk (agent A)\\n'  > notes.txt   # agent A",
        "$ printf 'shopping list\\n- bread (agent B)\\n' > notes.txt   # agent B",
        "$ cat notes.txt",
        final.decode().rstrip("\n"),
    ]
    return lines, final


def guarded(work):
    f = work / "notes.txt"
    f.write_bytes(ORIGINAL)
    root = ["--root", "."]
    lines = ["$ hash --root . notes.txt        # A and B both read it, and both see H1"]
    status, out = tool("hash", *root, "notes.txt", cwd=work)
    lines.append(short(out.splitlines()[0]))
    h1 = json.loads(out.splitlines()[0])["hex"]

    lines.append("$ printf 'shopping list\\n- milk (agent A)\\n' | write --root . --if-sha256 H1 --stdin notes.txt   # agent A")
    status_a, out_a = tool("write", *root, "--if-sha256", h1, "--stdin", "notes.txt", stdin=ORIGINAL + LINE_A, cwd=work)
    lines.append(short(out_a))
    lines.append("$ printf 'shopping list\\n- bread (agent B)\\n' | write --root . --if-sha256 H1 --stdin notes.txt   # agent B, stale")
    status_b, out_b = tool("write", *root, "--if-sha256", h1, "--stdin", "notes.txt", stdin=ORIGINAL + LINE_B, cwd=work)
    lines.append(short(out_b))
    lines.append("$ echo $?")
    lines.append(str(status_b))

    # B recovers: re-read, re-apply its edit to what is there now, write with the new hash.
    current = f.read_bytes()
    h2 = json.loads(out_b)["error"]["detail"]["actual_sha256"]
    assert h2 == hashlib.sha256(current).hexdigest()
    lines.append("$ # agent B re-reads (the refusal carried the new hash, H2), re-applies its line, and retries")
    lines.append("$ printf 'shopping list\\n- milk (agent A)\\n- bread (agent B)\\n' | write --root . --if-sha256 H2 --stdin notes.txt")
    status_c, out_c = tool("write", *root, "--if-sha256", h2, "--stdin", "notes.txt", stdin=current + LINE_B, cwd=work)
    lines.append(short(out_c))
    final = f.read_bytes()
    lines.append("$ cat notes.txt")
    lines.append(final.decode().rstrip("\n"))
    return lines, final, (status_a, status_b, status_c), out_b


def transcript():
    with tempfile.TemporaryDirectory(prefix="demo-race-") as tmp:
        work = pathlib.Path(tmp)
        (work / "classic").mkdir()
        (work / "guarded").mkdir()
        classic_lines, classic_final = classic(work / "classic")
        guarded_lines, guarded_final, statuses, refusal = guarded(work / "guarded")
    md = [
        BEGIN,
        "",
        "**With plain writes**, the second write wins and agent A's line is gone. Nobody is told:",
        "",
        "```console",
        *classic_lines,
        "```",
        "",
        "**With `write --if-sha256`**, the stale write is refused, and the refusal carries what the agent needs to retry:",
        "",
        "```console",
        *guarded_lines,
        "```",
        "",
        END,
    ]
    outcome = {
        "classic_lost_a": LINE_A not in classic_final,
        "guarded_kept_both": LINE_A in guarded_final and LINE_B in guarded_final,
        "statuses": statuses,
        "refusal_rule": json.loads(refusal)["error"]["rule"],
    }
    return "\n".join(md) + "\n", outcome


def fields(doc, *keys):
    """The named members of a JSON line, as one compact JSON object."""
    return json.dumps({k: doc[k] for k in keys}, separators=(",", ":"), ensure_ascii=False)


def short_flow():
    """The same run as `transcript`, shortened: the lost update, then the guarded
    writes with selected fields of each JSON line."""
    with tempfile.TemporaryDirectory(prefix="demo-flow-") as tmp:
        work = pathlib.Path(tmp)
        (work / "classic").mkdir()
        (work / "guarded").mkdir()
        classic_lines, _ = classic(work / "classic")
        w = work / "guarded"
        (w / "notes.txt").write_bytes(ORIGINAL)
        root = ["--root", "."]
        _, out = tool("hash", *root, "notes.txt", cwd=w)
        h1 = json.loads(out.splitlines()[0])["hex"]
        _, out_a = tool("write", *root, "--if-sha256", h1, "--stdin", "notes.txt", stdin=ORIGINAL + LINE_A, cwd=w)
        a = json.loads(out_a)
        status_b, out_b = tool("write", *root, "--if-sha256", h1, "--stdin", "notes.txt", stdin=ORIGINAL + LINE_B, cwd=w)
        b = json.loads(out_b)["error"]
        current = (w / "notes.txt").read_bytes()
        h2 = b["detail"]["actual_sha256"]
        _, out_c = tool("write", *root, "--if-sha256", h2, "--stdin", "notes.txt", stdin=current + LINE_B, cwd=w)
        c = json.loads(out_c)
        final = (w / "notes.txt").read_bytes()
    lines = [
        FLOW_BEGIN, "", "Two agents read `notes.txt` and each adds a line. **With plain writes** the second write wins and agent A's line is gone, and nobody is told:", "",
        "```console", *classic_lines[1:], "```", "",
        "With **guarded writes** (`write --if-sha256`) the stale write is refused, and the refusal carries what the agent needs to retry (selected fields of each JSON line):", "",
        "```console",
        "$ hash --root . notes.txt                 # A and B both read it: H1 is its hash",
        short(out.splitlines()[0]),
        "$ ... | write --root . --if-sha256 H1 --stdin notes.txt   # agent A adds its line",
        short(fields(a["data"], "path", "changed", "bytes", "after_sha256")),
        "$ ... | write --root . --if-sha256 H1 --stdin notes.txt   # agent B, stale",
        short(json.dumps({"rule": b["rule"], "hint": b["hint"], "repair": b["repair"], "detail": b["detail"]}, separators=(",", ":"))),
        "# exit status %d" % status_b,
        "$ ... | write --root . --if-sha256 H2 --stdin notes.txt   # agent B re-reads (H2 came with the refusal), re-applies, retries",
        short(fields(c["data"], "path", "changed", "bytes", "after_sha256")),
        "$ cat notes.txt",
        final.decode().rstrip("\n"),
        "```", "", FLOW_END,
    ]
    ok = LINE_A in final and LINE_B in final and b["rule"] == "precondition.hash-mismatch" and status_b == 5
    return "\n".join(lines) + "\n", ok


MAIN_RS = (
    "fn main() {\n    let total = add(2, 3);\n    println!(\"{}\", total);\n}\n\n"
    "fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n"
)
PACKAGE = '{"name": "demo", "version": "1.0.0", "deps": {"serde": "1.0", "rand": "0.8"}}\n'
ACCESS = "GET /a 200\nGET /b 200\nGET /c 404\nPOST /a 200\nGET /d 500\n"
# (the command typed, shown as typed; run from the project's directory)
TASKS = [
    ("seek", "search files for literal text", ["seek", "--root", ".", "add", "src/main.rs"], None),
    ("list", "the entries beneath a directory", ["list", "--root", ".", "--depth", "2", "--format", "text"], None),
    ("peek", "a range of lines, with numbers", ["peek", "--root", ".", "--lines", "2:3", "--format", "text", "src/main.rs"], None),
    ("jsonq", "one value from a JSON document", ["jsonq", "--root", ".", "-p", "/deps/serde", "package.json"], None),
    ("tally", "count and rank a field", ["tally", "--root", ".", "--field", "3", "--delim", " ", "--format", "text", "access.log"], None),
    ("hash", "a file's SHA-256", ["hash", "--root", ".", "package.json"], None),
    ("write", "create a file, or replace it only if it is what you think",
     ["write", "--root", ".", "--create", "--stdin", "NOTES.md"], b"hello\n"),
    ("replace", "change exact text, here as a dry run", ["replace", "--root", ".", "--old", "a + b", "--new", "a.wrapping_add(b)", "--dry-run", "src/main.rs"], None),
    ("move", "rename in place, never over an existing name", ["move", "--root", ".", "--dry-run", "NOTES.md", "NOTES-2026.md"], None),
]


def shell_quote(a):
    import shlex
    return shlex.quote(a)


def tasks_section():
    lines = [TASKS_BEGIN, ""]
    with tempfile.TemporaryDirectory(prefix="demo-tasks-") as tmp:
        w = pathlib.Path(tmp)
        (w / "src").mkdir()
        (w / "src" / "main.rs").write_text(MAIN_RS)
        (w / "package.json").write_text(PACKAGE)
        (w / "access.log").write_text(ACCESS)
        for name, what, argv, stdin in TASKS:
            status, out = tool(argv[0], *argv[1:], stdin=stdin or b"", cwd=w)
            cmd = " ".join(shell_quote(x) for x in argv)
            if stdin:
                cmd = "printf 'hello\\n' | " + cmd
            lines += ["**`%s`**: %s." % (name, what), "", "```console", "$ " + cmd, short(out)]
            if status != 0:
                lines.append("# exit status %d" % status)
            lines += ["```", ""]
    lines.append(TASKS_END)
    return "\n".join(lines) + "\n"


def splice(text, begin, end, section):
    if begin not in text or end not in text:
        sys.exit("a file has no %s markers" % begin.split()[0])
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return head + section.rstrip("\n") + tail


def regenerated(full, flow, tasks):
    """What README.md and docs/reference.md should hold."""
    return {
        README: splice(splice(README.read_text(), FLOW_BEGIN, FLOW_END, flow), TASKS_BEGIN, TASKS_END, tasks),
        REFERENCE: splice(REFERENCE.read_text(), BEGIN, END, full),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--update-readme", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    for name in ("hash", "write", "seek", "list", "peek", "jsonq", "tally", "replace", "move"):
        if not (BUILD / name).exists():
            sys.exit(f"demo_race: build/{name} is missing; run `cancho build` first")
    section, outcome = transcript()
    flow, flow_ok = short_flow()
    tasks = tasks_section()
    problems = []
    if not outcome["classic_lost_a"]:
        problems.append("plain writes did not lose agent A's line")
    if not outcome["guarded_kept_both"]:
        problems.append("guarded writes did not keep both lines")
    if outcome["statuses"] != (0, 5, 0):
        problems.append("exit statuses were %s, not (0, 5, 0)" % (outcome["statuses"],))
    if outcome["refusal_rule"] != "precondition.hash-mismatch":
        problems.append("the stale write was refused as %s" % outcome["refusal_rule"])
    if not flow_ok:
        problems.append("the short flow did not end as the full one does")
    want = regenerated(section, flow, tasks)
    if args.update_readme:
        for path, text in want.items():
            path.write_text(text)
    elif args.check:
        for path, text in want.items():
            if text != path.read_text():
                problems.append("%s's generated section is not what the script prints; run --update-readme" % path.relative_to(ROOT))
    else:
        print(section, end="")
    if problems:
        sys.exit("demo_race: " + "; ".join(problems))
    return 0


if __name__ == "__main__":
    sys.exit(main())
