#!/usr/bin/env python3
"""The authority manifest: derived by the compiler, embedded by the build,
gated against a ceiling (lex-sys docs/agent-toolbox.md D12, gate M6).

For every [[bin]] in lex-sys.toml:

1. pass 1: `lex-sys authority <sources> --std --output json`;
2. write manifests/<tool>.authority.json (the committed record) and
   generated/<tool>/built.ls, which holds the authority, the tool's schema
   (schemas/<tool>.v1.json) and the compiler pin as string literals;
3. pass 2: derive again with the new generated file and require the same
   report -- the fixed point. A string constant adds no label, so a
   manifest can describe the program that contains it (lex-sys A.11);
4. require every derived label to be within the tool's ceiling in tools.toml,
   `bounded` to be true and no foreign symbol.

    python3 scripts/manifest.py            # regenerate, then check
    python3 scripts/manifest.py --check    # change nothing; exit 1 on drift

`--check` also compares what each built binary prints (`build/<tool>
introspect`) with the fresh derivation when the binary exists, so a stale
build is caught as well as a stale file.

The compiler is $LEX_SYS, or `lex-sys` on PATH.
"""

import json
import os
import pathlib
import subprocess
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FORBIDDEN = {"ffi", "net_out", "net_in", "clock"}


def compiler():
    return os.environ.get("LEX_SYS", "lex-sys")


def project():
    with open(ROOT / "lex-sys.toml", "rb") as f:
        return tomllib.load(f)


def sources(entry):
    files = []
    for s in entry["sources"]:
        p = ROOT / s
        if p.is_dir():
            files.extend(sorted(str(x) for x in p.glob("*.ls")))
        else:
            files.append(str(p))
    return files


def derive(files):
    out = subprocess.run([compiler(), "authority", *files, "--std", "--output", "json"],
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit("lex-sys authority failed:\n" + out.stdout + out.stderr)
    return json.loads(out.stdout)


def compact(value):
    return json.dumps(value, separators=(",", ":"), ensure_ascii=True)


def literal(text):
    """A lex-sys string literal: six escapes, no others, one line."""
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 32:
            sys.exit("a control character cannot be written in a lex-sys literal")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def generated(authority, schema, pin):
    return """edition 5;

module toolbox.built;

// Generated by scripts/manifest.py -- do not edit. The compiler's authority
// report for this tool, the tool's JSON Schema, and the compiler it was
// written for, as `introspect` prints them (lex-sys docs/agent-toolbox.md D12).

pub fn authority() -> [] &static [byte] {
    return %s;
}

pub fn schema() -> [] &static [byte] {
    return %s;
}

pub fn compiler() -> [] &static [byte] {
    return %s;
}
""" % (literal(compact(authority)), literal(compact(schema)), literal(pin))


def label_text(label):
    if label["argument"] is None:
        return label["name"]
    return '%s("%s")' % (label["name"], label["argument"])


def gate(tool, authority, ceilings):
    problems = []
    ceiling = ceilings.get(tool)
    if ceiling is None:
        return ["%s: no ceiling in tools.toml" % tool]
    allowed = set(ceiling.get("allow", []))
    if not authority.get("bounded", False):
        problems.append("%s: bounded is false" % tool)
    if authority.get("foreign_symbols"):
        problems.append("%s: foreign symbols %s" % (tool, authority["foreign_symbols"]))
    for label in authority["labels"]:
        text = label_text(label)
        if label["name"] in FORBIDDEN:
            problems.append("%s: %s is forbidden to every tool" % (tool, text))
        if text not in allowed:
            problems.append("%s: %s is not within the ceiling in tools.toml" % (tool, text))
    return problems


def introspected(tool):
    binary = ROOT / "build" / tool
    if not binary.exists():
        return None
    out = subprocess.run([str(binary), "introspect"], capture_output=True, text=True)
    if out.returncode != 0:
        return "introspect exited %d" % out.returncode
    return json.loads(out.stdout)["authority"]


def main():
    check = "--check" in sys.argv[1:]
    proj = project()
    pin = proj["package"]["lex-sys"]
    with open(ROOT / "tools.toml", "rb") as f:
        ceilings = tomllib.load(f)
    bins = proj.get("bin", [])
    problems = []
    if len(bins) > ceilings.get("max_tools", 10):
        problems.append("%d tools; tools.toml allows %d (D1)" % (len(bins), ceilings["max_tools"]))
    for entry in bins:
        tool = entry["name"]
        files = sources(entry)
        first = derive(files)
        schema = json.loads((ROOT / "schemas" / ("%s.v1.json" % tool)).read_text())
        record = ROOT / "manifests" / ("%s.authority.json" % tool)
        built = ROOT / "generated" / tool / "built.ls"
        record_text = json.dumps(first, indent=2) + "\n"
        built_text = generated(first, schema, pin)
        if check:
            if not record.exists() or record.read_text() != record_text:
                problems.append("%s: %s is not the compiler's report" % (tool, record.relative_to(ROOT)))
            if not built.exists() or built.read_text() != built_text:
                problems.append("%s: %s is stale" % (tool, built.relative_to(ROOT)))
            embedded = introspected(tool)
            if embedded is not None and embedded != first:
                problems.append("%s: build/%s introspect prints an authority that is not the compiler's (a stale build?)" % (tool, tool))
        else:
            record.parent.mkdir(exist_ok=True)
            record.write_text(record_text)
            built.parent.mkdir(parents=True, exist_ok=True)
            built.write_text(built_text)
            second = derive(files)
            if second != first:
                problems.append("%s: no fixed point -- embedding the manifest changed the authority" % tool)
        problems.extend(gate(tool, first, ceilings))
        labels = ", ".join(label_text(l) for l in first["labels"])
        print("%-8s %s" % (tool, labels))
    for p in problems:
        print("FAIL " + p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
